services:
  kcn_alertest:
    image: kizyanov/kcn_alertest:latest
    build: .
    container_name: kcn_alertest
    tty: true
    restart: always
    environment:
      - KEY=123
      - SECRET=123
      - PASSPHRASE=123
      - BASE_KEEP=123
      - ALLCURRENCY=BTC,ETH
      - IGNORECURRENCY=123
      - TELEGRAM_BOT_API_KEY=123
