services:
  kcn_composter:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    env_file:
      - .env

  # composter_1:
  #   image: kizyanov/kcn_composter:latest
  #   container_name: kcn_composter_1
  #   tty: true
  #   restart: always
  #   depends_on:
  #    - balancer
  #    - processor
  #    - nats
  #   links:
  #    - nats:nats
  #   env_file:
  #     - .env
  #   environment:
  #     - START_POS=0
  #     - COUNT_POS=20

  # composter_2:
  #   image: kizyanov/kcn_composter:latest
  #   container_name: kcn_composter_2
  #   tty: true
  #   restart: always
  #   depends_on:
  #    - balancer
  #    - processor
  #    - nats
  #   links:
  #    - nats:nats
  #   env_file:
  #     - .env
  #   environment:
  #     - START_POS=20
  #     - COUNT_POS=20

  # composter_3:
  #   image: kizyanov/kcn_composter:latest
  #   container_name: kcn_composter_3
  #   tty: true
  #   restart: always
  #   depends_on:
  #    - balancer
  #    - processor
  #    - nats
  #   links:
  #    - nats:nats
  #   env_file:
  #     - .env
  #   environment:
  #     - START_POS=40
  #     - COUNT_POS=20

  # composter_4:
  #   image: kizyanov/kcn_composter:latest
  #   container_name: kcn_composter_4
  #   tty: true
  #   restart: always
  #   depends_on:
  #    - balancer
  #    - processor
  #    - nats
  #   links:
  #    - nats:nats
  #   env_file:
  #     - .env
  #   environment:
  #     - START_POS=60
  #     - COUNT_POS=20

  # composter_5:
  #   image: kizyanov/kcn_composter:latest
  #   container_name: kcn_composter_5
  #   tty: true
  #   restart: always
  #   depends_on:
  #    - balancer
  #    - processor
  #    - nats
  #   links:
  #    - nats:nats
  #   env_file:
  #     - .env
  #   environment:
  #     - START_POS=80
  #     - COUNT_POS=20

  # composter_6:
  #   image: kizyanov/kcn_composter:latest
  #   container_name: kcn_composter_6
  #   tty: true
  #   restart: always
  #   depends_on:
  #    - balancer
  #    - processor
  #    - nats
  #   links:
  #    - nats:nats
  #   env_file:
  #     - .env
  #   environment:
  #     - START_POS=100
  #     - COUNT_POS=20

  orderest:
    image: kizyanov/kcn_orderest:latest
    container_name: kcn_orderest
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - processor
      - nats

  balancer:
    image: kizyanov/kcn_balancer:latest
    container_name: kcn_balancer
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - processor
      - nats
    links:
     - nats:nats

  processor:
    image: kizyanov/kcn_processor:latest
    build: .
    container_name: kcn_processor
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - nats
    links:
     - nats:nats

  alertest:
    image: kizyanov/kcn_alertest:latest
    container_name: kcn_alertest
    tty: true
    restart: always
    env_file:
      - .env
      
  nats:
    image: nats:2.10.16-alpine3.19
    container_name: nats
    restart: always
    hostname: nats
    command: --js

