services:
  composter_1:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter_1
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    environment:
      - CURRENCY=OP,KCS,WIF,IMX,SUI,APT,ICP,BTC,APE,FRONT,ADA,PEPE,PEPE2,BTC,ETH,AVAX,NOT,TON
  
  composter_2:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter_2
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    environment:
      - CURRENCY=DYM,BONK,LTC,BCH

  balancer:
    image: kizyanov/kcn_balancer:latest
    container_name: kcn_balancer
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - processor
      - nats
    links:
     - nats:nats

  processor:
    image: kizyanov/kcn_processor:latest
    build: .
    container_name: kcn_processor
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - nats
    links:
     - nats:nats

  nats:
    image: nats:2.10.16-alpine3.19
    container_name: nats
    restart: always
    hostname: nats
    command: --js

