services:
  composter_1:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter_1
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    environment:
      - CURRENCY=OP,SEI,BNB,CRV,GAL,KCS,DOT,EGLD,JTO,LDO,WIF,XRP,UNI,MANA,RLC,IMX,MATIC,THETA,SAND,SNX
  
  composter_2:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter_2
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    environment:
      - CURRENCY=SUI,TRX,ALICE,GLMR,ORN,APT,BCH,SUSHI,C98,MANTA,ICP,AAVE,CELO,BIGTIME,APE,BTC,LTC,NEO,YFI,FRONT

  composter_3:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter_3
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    environment:
      - CURRENCY=ETH,COMP,AXS,MKR,ZETA,ARB,AVAX,PYR,QNT,XTZ,SOL,AR,UMA,ILV,WOO,ORDI,RNDR,MASK,METIS,SUPER

  composter_4:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter_4
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    environment:
      - CURRENCY=INJ,NEAR,CAKE,LISTA,FLOW,LPT,FIL,ADA,DASH,YGG,ENS,RUNE,ONDO,KSM,XPR,ATOM,WLD,FTM,ETC,CHR

  composter_5:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter_5
    tty: true
    restart: always
    depends_on:
     - balancer
     - processor
     - nats
    links:
     - nats:nats
    environment:
      - CURRENCY=LINK,STX,LUNA,ZEC,PEPE2,TON,FET,DYM,MOVR,ELON,NOT,JUP,DYDX,FXS,BOME,TIA,DAO,KDA,ERN,PEPE

  orderest:
    image: kizyanov/kcn_orderest:latest
    container_name: kcn_orderest
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - processor
      - nats

  balancer:
    image: kizyanov/kcn_balancer:latest
    container_name: kcn_balancer
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - processor
      - nats
    links:
     - nats:nats

  processor:
    image: kizyanov/kcn_processor:latest
    build: .
    container_name: kcn_processor
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - nats
    links:
     - nats:nats

  alertest:
    image: kizyanov/kcn_alertest:latest
    container_name: kcn_alertest
    tty: true
    restart: always
    env_file:
      - .env
      
  nats:
    image: nats:2.10.16-alpine3.19
    container_name: nats
    restart: always
    hostname: nats
    command: --js

