services:
  kcn_composter:
    image: kizyanov/kcn_composter:latest
    container_name: kcn_composter
    tty: true
    restart: always
    depends_on:
     - kcn_balancer
     - kcn_processor
     - kcn_nats
    links:
     - kcn_nats:kcn_nats
    env_file:
      - .env

  kcn_orderest:
    image: kizyanov/kcn_orderest:latest
    container_name: kcn_orderest
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - kcn_processor
      - kcn_nats

  kcn_balancer:
    image: kizyanov/kcn_balancer:latest
    container_name: kcn_balancer
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - kcn_processor
      - kcn_nats
    links:
     - kcn_nats:kcn_nats

  kcn_processor:
    image: kizyanov/kcn_processor:latest
    container_name: kcn_processor
    tty: true
    restart: always
    env_file:
      - .env
    depends_on:
      - kcn_nats
    links:
     - kcn_nats:kcn_nats

  kcn_alertest:
    image: kizyanov/kcn_alertest:latest
    container_name: kcn_alertest
    tty: true
    restart: always
    env_file:
      - .env
      
  kcn_nats:
    image: nats:2.10.22-alpine3.20
    container_name: kcn_nats
    restart: always
    hostname: kcn_nats
    command: --js

