services:
  kcn_composter:
    image: kizyanov/kcn_composter:latest
    build: .
    container_name: kcn_composter
    tty: true
    restart: always
    # links:
    #  - nats:nats
    environment:
      - KEY=123
      - SECRET=123
      - PASSPHRASE=123
      - BASE_KEEP=123
      - ALLCURRENCY=BTC,ETH
      - IGNORECURRENCY=123
      - TELEGRAM_BOT_API_KEY=123
      - TELEGRAM_BOT_CHAT_ID=123
  # nats:
  #   image: nats:2.10.22-alpine3.20
  #   container_name: nats
  #   restart: always
  #   hostname: nats
  #   command: --js

