services:
  composter:
    image: kizyanov/kcn_composter:latest
    build: .
    container_name: kcn_composter
    tty: true
    restart: always
    links:
     - nats:nats
    environment:
      - CURRENCY=OP,KCS,WIF,IMX,SUI,APT,ICP,BTC,APE,FRONT

  nats:
    image: nats:2.10.16-alpine3.19
    container_name: nats
    restart: always
    hostname: nats
    command: --js

