services:
  balancer:
    image: kizyanov/kcn_balancer:latest
    build: .
    container_name: kcn_balancer
    tty: true
    restart: always
    # links:
    #  - nats:nats

  # nats:
  #   image: nats:2.10.16-alpine3.19
  #   container_name: nats
  #   restart: always
  #   hostname: nats
  #   command: --js

